PersonelWebSite/Areas/Member/Controllers/EgitimController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Abstract;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PersonelWebSite.Areas.Member.Controllers
{
    [Area("Member")]
    [Route("Member/[controller]/[action]")]
    public class EgitimController : Controller
    {
        EducationAndExpericenceManager EducationAnd = new EducationAndExpericenceManager(new EfEducationAndExpericenceDal());


        public IActionResult Index()
        {
            var values = EducationAnd.GetList();
            return View(values);
        }


        
        public IActionResult Delete(int id)
        {
            var values = EducationAnd.GetByID(id);
            EducationAnd.Delete(values);
            return RedirectToAction("Index", "Profile", new { area = "Member" });
        }

        [HttpGet]
        public IActionResult EgitimEkle()
        {

            return View();
        }

        [HttpPost]
        public IActionResult EgitimEkle(EducationAndExpericence e)
        {
            e.EducationAndExpericenceStatus = Request.Form["title"].ToString();
            EducationAnd.Insert(e);
            return RedirectToAction("Index");
        }



        [HttpGet]
        public IActionResult EgitimGüncelle(int id)
        {
            EducationAndExpericence educationAnd2 = EducationAnd.GetByID(id);

            return View(educationAnd2);
        }

        [HttpPost]
        public IActionResult EgitimGüncelle(EducationAndExpericence education)
        {
            EducationAndExpericence educationAnd22 = EducationAnd.GetByID(education.EducationAndExpericenceID);

            educationAnd22.EducationAndExpericenceTitle = education.EducationAndExpericenceTitle;
            educationAnd22.EducationAndExpericenceLittleTitle = education.EducationAndExpericenceLittleTitle;
            educationAnd22.EducationAndExpericenceDescription = education.EducationAndExpericenceDescription;
            educationAnd22.EducationAndExpericenceDate = education.EducationAndExpericenceDate;
            educationAnd22.EducationAndExpericenceStatus = Request.Form["title"].ToString();



            EducationAnd.Update(educationAnd22);

            return RedirectToAction("Index", "Profile", new { area = "Member" });
        }
    }
}

PersonelWebSite/Areas/Member/Views/Egitim/EgitimEkle.cshtml
@using EntityLayer.Abstract
@model EducationAndExpericence
@{
    ViewData["Title"] = "EgitimEkle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<form class="form-group m-4" method="post">
    @Html.LabelFor(x => x.EducationAndExpericenceTitle)
    @Html.TextBoxFor(x => x.EducationAndExpericenceTitle, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.EducationAndExpericenceLittleTitle)
    @Html.TextBoxFor(x => x.EducationAndExpericenceLittleTitle, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.EducationAndExpericenceDescription)
    @Html.TextBoxFor(x => x.EducationAndExpericenceDescription, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.EducationAndExpericenceDate)
    @Html.TextBoxFor(x => x.EducationAndExpericenceDate, new { @class = "form-control" })
    <br />

    <div class="form-field email">
        <label class="label" for="email">Deneyim mi eğitim seçiniz *</label>
        <select name="title" required>
            <option value="Expericence">Expericence</option>
            <option value="Education">Education</option>
        </select>
    </div>
    <button class="btn btn-info">Ekle</button>
</form>

PersonelWebSite/Areas/Member/Views/Egitim/EgitimGüncelle.cshtml
@model EntityLayer.Abstract.EducationAndExpericence
@{
    ViewData["Title"] = "EgitimGüncelle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>EgitimGüncelle</h1>
<br />
<form class="form-group" method="post">
    @Html.Label("ID")
    @Html.TextBoxFor(x => x.EducationAndExpericenceID, new { @class = "form-control" })
    <br />
    @Html.Label("Başlık")
    @Html.TextBoxFor(x => x.EducationAndExpericenceTitle, new { @class = "form-control" })
    <br />
    @Html.Label("Küçük Başlık")
    @Html.TextAreaFor(x => x.EducationAndExpericenceLittleTitle, 10, 3, new { @class = "form-control" })
    <br />
    @Html.Label("Açıklama")
    @Html.TextAreaFor(x => x.EducationAndExpericenceDescription, 10, 3, new { @class = "form-control" })

    <br />
    @Html.Label("İçerik")
    @Html.TextAreaFor(x => x.EducationAndExpericenceDate, 10, 3, new { @class = "form-control" })
    <br />
    <div class="form-field email">
        <label class="label" for="email">Deneyim mi eğitim seçiniz *</label>
        <select name="title" required>
            <option value="Expericence">Expericence</option>
            <option value="Education">Education</option>
        </select>
    </div>
    <button class="btn btn-info">Güncelle</button>



</form>

PersonelWebSite/Areas/Member/Views/Egitim/Index.cshtml
@using EntityLayer.Abstract
@model List<EducationAndExpericence>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Eğitim Alanı</h1>


<table class="table table-bordered">
    <tr>

        <th>Başlık</th>
        <th>Küçük Başlık</th>
        <th>Açıklama</th>
        <th>Durumu</th>
        <th>Tarih aralığı</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.EducationAndExpericenceTitle</td>
            <td>@item.EducationAndExpericenceLittleTitle</td>
            <td>@item.EducationAndExpericenceDescription</td>
            <td>@item.EducationAndExpericenceStatus</td>
            <td>@item.EducationAndExpericenceDate</td>
            <td>
                @Html.ActionLink("SİL", "Delete", "Egitim", new { area = "Member", id = item.EducationAndExpericenceID })
            </td>
        <td>
            @Html.ActionLink("Güncelle", "EgitimGüncelle", "Egitim", new { area = "Member",id =  item.EducationAndExpericenceID})
                </td>
        </tr>
    }@*571632Reis.*@
</table>